dist: bionic
os: linux
language: shell
branches:
  only:
    - master
env:
  global:
    - IMAGE_NAME="orbnedron/radarr"
git:
  depth: false
services:
  - docker
notifications:
  email:
    recipients:
      - orbnedron@nordenbro.com
    on_success: change
    on_failure: always

before_install:
  - sudo apt-get install -y jq > /dev/null

before_script:
  - docker pull $IMAGE_NAME > /dev/null
  - export RADARR_VERSION="$(curl -sX GET "https://api.github.com/repos/Radarr/Radarr/releases/latest" | jq -r .name)"
script:
  - docker build --build-arg RADARR_VERSION=${RADARR_VERSION} --pull --cache-from $IMAGE_NAME --tag $IMAGE_NAME .
  - docker run --name radarr -d -p 7878:7878 ${IMAGE_NAME}
  - sleep 20
  - docker logs radarr
  - curl --retry 20 --retry-connrefused --retry-delay 3 -s http://localhost:7878 >/dev/null 2>&1
  - docker stop radarr
  - docker rm -f radarr
  - docker tag $IMAGE_NAME:latest ${IMAGE_NAME}:v${RADARR_VERSION}
  - docker images

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
